server:
  port: 4550

management:
  endpoints:
    web:
      base-path: /

spring:
  main:
    allow-bean-definition-overriding: true  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
  application:
    name: Cmc Claim Submit API

idam:
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4552}
    totp_secret: ${IDAM_S2S_KEY:AAAAAAAAAAAAAAAB}
    microservice: cmc_claim_store

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}